{% set name = "monai" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Project-MONAI/MONAI/archive/refs/tags/{{ version }}.tar.gz
  sha256: 66914a90db8d9e1146ab2e9debb4a53075f8d419f0068593ea2787bd12f3c68c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.24, <3.0
    - pytorch >=2.4.1

test:
  imports:
    - monai
    - monai.losses.dice
    - monai.networks.nets.unet
    - monai.transforms.spatial.dictionary
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://monai.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: AI Toolkit for Healthcare Imaging
  description: |
    MONAI is a PyTorch-based, open-source framework for deep learning in
    healthcare imaging, part of PyTorch Ecosystem.
  doc_url: https://docs.monai.io/en/stable/
  dev_url: https://github.com/Project-MONAI/MONAI
  doc_source_url: https://github.com/Project-MONAI/MONAI/tree/dev/docs

extra:
  recipe-maintainers:
    - KumoLiu
    - mdraw
    - wyli
